### ISSUE TITLE
HTTP 406 (Not Accpetable) in client_credentials grant

### ISSUE THREAD

**Issue by h0ru5** [FrontierPsychiatrist/spring-oauth-example#3]
Hi,

encountering 406 errors when trying to run the client credentials flow.

To reproduce: clone & gradle run the oauth-server, run example curl client

Platform: win32, oracle jdk 8

Could not find a workaround so far.
Possibly related: http://stackoverflow.com/questions/26185066/spring-4-0-oauth-2-not-working

**Comment by FrontierPsychiatrist** [comment]
Can you try to change the curl call to

```
TOKEN=`curl -H "Accept: application/json" -s -u curl-client:client-secret localhost:8081/oauth/token\?grant_type=client_credentials | egrep -o '[a-f0-9-]{20,}'`
```

**Comment by h0ru5** [comment]
Ok, I didn't write it up there, but the 406 happens regardless of sending the Accept header. (e.g. also with a rest client like Postman)
It seems to be related  generally with v2.0.5 in certain  setups - haven't gotten deeper yet.

**Comment by FrontierPsychiatrist** [comment]
Ok then, that's strange. I'll try to reproduce it on OSX, don't have a Windows development setup.

For further investigation you could turn on more granular logging for Spring Security/MVC in the [logback configuration](https://github.com/FrontierPsychiatrist/spring-oauth-example/blob/master/oauth-server/src/main/resources/logback.xml) and see if you can spot the error.

```
<logger name="org.springframework.web" level="debug"/>
<logger name="org.springframework.security" level="debug"/>
```

**Comment by FrontierPsychiatrist** [comment]
Hm, I can't reproduce it on OSX.

**Comment by h0ru5** [comment]
It works for me now, but I changed too many things to reproduce what was causing the problem. I suspect my gradle setup.
 (proxying over a local artifactory etc.) 
Anyway, it works, even on a clean checkout, so I'm closing this.

**Comment by FrontierPsychiatrist** [comment]
Glad to hear that! Let me know if there are any more questions.
