### ISSUE TITLE
Not getting refresh_token and "Unsupported grant type: password"

### ISSUE THREAD

**Issue by thiagolocatelli** [FrontierPsychiatrist/spring-oauth-example#5]
Hi, two things.

I am executing the following curl command:

curl -X POST -u curl-client:client-secret http://localhost:8081/oauth/token -H "Accept: application/json" -d "password=user&username=user&grant_type=client_credentials&scope=read%20write&client_secret=client-secret&client_id=curl-client"

and I am getting the following response without the refresh_token

{"access_token":"c42ee640-44d1-4217-a608-6eaeb1ce9f14","token_type":"bearer","expires_in":4186,"scope":"read write"}

I have changed the client in the admin UI to support password, refresh_token and client_credentials, but the refresh token is not being retrieve. Also, it only works with grant_type=client_credentials, grant_type=password does not work.

Any ideas?

**Comment by thiagolocatelli** [comment]
Fixed.

**Comment by Dayslar** [comment]
??

**Comment by FrontierPsychiatrist** [comment]
Sorry just got around to look at this now. What was the problem? I haven't tried refresh tokens yet.
