### ISSUE TITLE
issue with authorization code support

### ISSUE THREAD

**Issue by acelabs88** [FrontierPsychiatrist/spring-oauth-example#8]
First of all, thanks for the great example - it really helped me to get a framework up in a short time.

I am trying to get the authorization code support working, but have encountered some problems. Here is what I did.

From the oath admin page, I configured the client as below:
<img width="849" alt="1" src="https://user-images.githubusercontent.com/26646665/29542192-f18f85aa-870b-11e7-8b7c-5e31aab710a7.png">

Make a http get using browser: http://localhost:8081/oauth/authorize?client_id=my-web-client&response_type=code&redirect_uri=http://localhost:9090/web&scope=read

After login, I see oath server redirected me to: http://localhost/web?code=tFMD1y

So far so good.

Then I make another http get using browser: http://locahost:8081/oauth/token?client_id=my-web-client&client_secret=xxxxxxxxxxxxxxxx&grant_type=authorization_code&code= tFMD1y&redirect_uri=http://localhost:9090/web

However instead of returning me the authorisation token, I was prompted for login again with popup dialog. And even after inputting the correct credentials, the login dialog will prompt again. If I cancel the login dialog I got the following error:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Aug 22 07:37:26 CST 2017
There was an unexpected error (type=Unauthorized, status=401).
Full authentication is required to access this resource
```

Am I doing something wrong? Is the authorization_code support available out of the box?

**Comment by FrontierPsychiatrist** [comment]
Hey! I think I haven't tested the code yet, I'll have to reproduce that.

I think it could be that you need to give the client id and client secret as basic authentication details instead of query parameters in this request:

    http://locahost:8081/oauth/token?client_id=my-web-client&client_secret=xxxxxxxxxxxxxxxx&grant_type=authorization_code&code= tFMD1y&redirect_uri=http://localhost:9090/web

Could you try that?

**Comment by FrontierPsychiatrist** [comment]
I just tested what I proposed, for me it worked with one more change: The last request (to `/oauth/token`) has to be a `POST` request.

```
% curl -X POST --user my-web-client localhost:8081/oauth/token\?grant_type=authorization_code\&code=xlgYS4\&redirect_uri=http://localhost:9090/web
Enter host password for user 'my-web-client':
{"access_token":"75b40bc0-a35e-41dd-a602-5bf45a35b020","token_type":"bearer","expires_in":7088,"scope":"read"}
```

**Comment by acelabs88** [comment]
Sorry for the late reply. Yes using your proposed procedure solved the problem. Thanks!

**Comment by FrontierPsychiatrist** [comment]
Sure thing!
